server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver  #com.mysql.cj.jdbc.Driver
    url: jdbc:p6spy:mysql://121.41.36.222:3306/freelance?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    host: 121.41.36.222
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0




#mybatis-plus 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)




